services:
  tapride-frontend:
    container_name: tapride-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:3000" # maps host 8070 to container 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
